name: Update Redirect

on:
  schedule:
    - cron: '0 0 * * *'   # daily at midnight UTC
  workflow_dispatch:      # allow manual trigger

jobs:
  update-redirect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run update_redirect.py
        run: python update_redirect.py

      - name: Check if index.html changed
        id: check_diff
        run: |
          git diff --name-only HEAD | grep '^index\.html$' \
          && echo "changed=true" >> "$GITHUB_OUTPUT" \
          || echo "changed=false" >> "$GITHUB_OUTPUT"

      - name: Commit and push if changed
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update redirect target (auto)"
          git push

      - name: Create or update notification issue
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          ISSUE=$(gh issue list --search "Redirects updated" --state open --json number -q '.[0].number')
          if [ -z "$ISSUE" ]; then
            gh issue create \
              --title "Redirects updated" \
              --body "The file \`index.html\` was updated in [this commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})." \
              --label documentation
          else
            gh issue comment "$ISSUE" \
              --body "The file \`index.html\` was updated again in [this commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}